# Generated by Django 3.2.9 on 2021-11-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_new',
        ),
    ]
